imageflow-raw:
  autoredeploy: true
  entrypoint: '/bin/bash -c "sudo chown -R imageflow /home/imageflow/  && sync && /home/imageflow/imageflow_server --version && /home/imageflow/imageflow_server diagnose --smoke-test-core && cat /proc/cpuinfo && /home/imageflow/imageflow_server start --demo --bind-address 0.0.0.0 --port 3000 --data-dir /home/imageflow/data/"'
  environment:
    - RUST_BACKTRACE=1
  image: 'imazen/imageflow_server_unsecured:latest'
  ports:
    - '3000:3000'
  privileged: true
  restart: always
  roles:
    - global
  volumes:
    - '/mnt/imageflow/server_data:/home/imageflow/data'