volume-config:
  image: imazen/nginx_template
  autoredeploy: false

volume-certs:
  image: imazen/nginx_template
  volumes:
      - "/etc/nginx/certs"
  autoredeploy: false


nginx-proxy:
  image: nginx:alpine
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - volume-certs
    - volume-config


nginx-gen:
  image: imazen/docker-gen-cloud
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
  volumes_from:
    - volume-certs
    - volume-config
  entrypoint: /usr/local/bin/docker-gen -notify-output -notify "./restart_service.sh" -watch -only-exposed -wait 10s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  environment:
    - PROXY_SERVICE_ENV_VAR=nginx-proxy
  roles:
   - global

letsencrypt-nginx-proxy:
  image: imazen/docker-letsencrypt-nginx-proxy-companion
  volumes_from:
    - volume-certs
    - volume-config
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
  environment:
    - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    - ACME_CA_URI=https://acme-v01.api.letsencrypt.org/directory
  roles:
    - global


imageflow-hidden:
  autoredeploy: true
  deployment_strategy: high_availability
  entrypoint: '/bin/bash -c "ulimit -c unlimited && sudo chown -R imageflow /home/imageflow/ && /home/imageflow/imageflow_server start --demo --bind-address 0.0.0.0 --port 3000 --data-dir /home/imageflow/data/"'
  target_num_containers: 2
  environment:
    - RUST_BACKTRACE=1
    - VIRTUAL_HOST=imageflow-demo-a.imazen.io,*.dockerapp.io, demo.imazen.io
    - VIRTUAL_PORT=3000
    - LETSENCRYPT_HOST=demo.imazen.io
    - LETSENCRYPT_EMAIL=support@imazen.io
  image: 'imazen/imageflow_server_unsecured:latest'
  expose:
    - '3000'
  restart: always
  roles:
    - global
  volumes:
    - '/volumes/imageflow/server_data:/home/imageflow/data'
papertrail:
  autoredeploy: true
  entrypoint: '/bin/logspout syslog+tls://[logs2].papertrailapp.com:[your papertrail port here]'
  image: 'gliderlabs/logspout:latest'
  restart: always
  roles:
    - global
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'

